# Generated by Django 4.2.20 on 2025-03-17 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('duration', models.IntegerField(default=24)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('file_object', models.FileField(blank=True, null=True, upload_to='otplink')),
                ('file_field', models.CharField(blank=True, default='file_object', max_length=100, null=True)),
                ('basename_field', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('encoding_field', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('mime_type_field', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('charset_field', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('modification_time_field', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('size_field', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='otplink_otp_content_36f498_idx')],
            },
        ),
    ]
