# Generated by Django 4.2.19 on 2025-03-13 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('instance_id', models.IntegerField()),
                ('file_field', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('duration', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Object',
                'verbose_name_plural': 'OTP Objects',
            },
        ),
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
