# Generated by Django 4.2.19 on 2025-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otplink", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
